version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - "8888:8888"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 8888
    command: -p 8888

  api:
    container_name: "api"
    restart: on-failure
    build: .
    ports:
      - "9090:9090"